-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Hyprland config

-- minimal/clean setup, muted colors, heavy blur

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})

-- programs that get launched on login moved down to the autostart block at the bottom of this file

hl.env("XCURSOR_SIZE", "24")

hl.env("HYPRCURSOR_SIZE", "24")

-- macOS style cursor, installed from the apple_cursor AUR package in install.sh
-- HYPRCURSOR_THEME doesn't actually ship a native hyprcursor version of this theme,
-- Hyprland just falls back to the regular Xcursor one when that happens, so this is fine
hl.env("XCURSOR_THEME", "macOS")

hl.env("HYPRCURSOR_THEME", "macOS")

local mainMod = "SUPER"

-- Secondary modifier for the "move window to workspace" and exit binds. Shift is used by default.
-- If the main modifier already contains Shift, those binds would collide with the primary ones
-- (the last definition wins), so Ctrl is used instead, or Alt if Ctrl is already part of the main modifier.
local secondMod = "SHIFT"
if string.find(mainMod, "SHIFT") then
    secondMod = "CTRL"
    if string.find(mainMod, "CTRL") then
        secondMod = "ALT"
    end
end

local terminal = "kitty"

local fileManager = "nautilus"

local menu = "wofi --show drun"

hl.config({
    input = {
        kb_layout = "us",
        follow_mouse = 1,
        touchpad = {
            natural_scroll = false,
        },
        sensitivity = 0,
    },
})

hl.config({
    general = {
        gaps_in = 6,
        gaps_out = 14,
        border_size = 2,
        resize_on_border = true,
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = { colors = { "rgba(e0e0e0ee)", "rgba(888888ee)" }, angle = 45 },
            inactive_border = "rgba(3a3a3aaa)",
        },
    },
})

hl.config({
    decoration = {
        rounding = 12,
        blur = {
            enabled = true,
            size = 8,
            passes = 3,
            vibrancy = 0.17,
            new_optimizations = true,
            ignore_opacity = true,
        },
        shadow = {
            enabled = true,
            range = 20,
            render_power = 3,
            color = "rgba(1a1a1aaa)",
        },
        active_opacity = 0.95,
        inactive_opacity = 0.85,
    },
})

hl.config({
    animations = {
        enabled = true,
    },
})
hl.curve("smoothOut", {
    type = "bezier",
    points = { { 0.36, 0 }, { 0.66, -0.56 } },
})
hl.curve("smoothIn", {
    type = "bezier",
    points = { { 0.25, 1 }, { 0.5, 1 } },
})
hl.curve("overshot", {
    type = "bezier",
    points = { { 0.05, 0.9 }, { 0.1, 1.05 } },
})
hl.animation({ leaf = "windows", enabled = true, speed = 5, bezier = "overshot", style = "slide" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 4, bezier = "smoothOut", style = "slide" })
hl.animation({ leaf = "border", enabled = true, speed = 8, bezier = "default" })
hl.animation({ leaf = "fade", enabled = true, speed = 5, bezier = "smoothIn" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "overshot", style = "slide" })

hl.config({
    dwindle = {
        preserve_split = true,
    },
})

hl.config({
    master = {
        new_status = "master",
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
    },
})

-- window rules, mostly just for the file manager and any picture-in-picture stuff

hl.window_rule({
    name  = "float_99",
    match = {
        class = "^(org\\.gnome\\.Nautilus)$",
    },
    float = true,
})

hl.window_rule({
    name  = "size_800_500_100",
    match = {
        class = "^(org\\.gnome\\.Nautilus)$",
    },
    size = "800 500",
})

hl.window_rule({
    name  = "float_101",
    match = {
        title = "^(Picture-in-Picture)$",
    },
    float = true,
})

hl.window_rule({
    name  = "pin_102",
    match = {
        title = "^(Picture-in-Picture)$",
    },
    pin = true,
})

-- cava widget, floats bottom right, no focus stealing, shows on every workspace
hl.window_rule({
    name  = "cava_float",
    match = {
        class = "^(cava-widget)$",
    },
    float = true,
    no_initial_focus = true,
    pin = true,
    size = "260 90",
    move = "monitor_w-280 monitor_h-110",
})

-- keybinds

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd(terminal))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. secondMod .. " + " .. "Q", hl.dsp.exit())

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd(fileManager))

hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())

hl.bind(mainMod .. " + " .. "D", hl.dsp.exec_cmd(menu))

hl.bind(mainMod .. " + " .. "P", hl.dsp.window.pseudo())

hl.bind(mainMod .. " + " .. "J", hl.dsp.layout("togglesplit"))

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

-- move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. secondMod .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. secondMod .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. secondMod .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. secondMod .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. secondMod .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. secondMod .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. secondMod .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. secondMod .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. secondMod .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. secondMod .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

-- screenshot stuff, region select then copies to clipboard

hl.bind("Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | wl-copy"))

hl.bind(mainMod .. " + " .. "Print", hl.dsp.exec_cmd("grim - | wl-copy"))

-- Volume and brightness. Requires wireplumber (wpctl) and brightnessctl.
-- "repeating" allows holding the key, "locked" keeps the binds active on the lock screen.

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 5%+"), { locked = true, repeating = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true, repeating = true })

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("mako")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("bash ~/.config/hypr/scripts/cava-widget.sh")
end)
