# wallpaper config, drop your image in ~/Pictures/wallpapers and point to it below
# splash = false just hides the little hyprland logo it puts in the corner

preload = ~/Pictures/wallpapers/main.png
wallpaper = ,~/Pictures/wallpapers/main.png
splash = false
